[package]
name = "hive-core-cli"
version = "0.1.9"
edition = "2021"
publish = false

[[bin]]
name = "hive-core"
path = "src/main.rs"

[dependencies]
hive-protocol = { path = "../hive-protocol" }
chrono = { version = "0.4", features = ["clock", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "0.8", features = ["v4"] }
libc = "0.2"
